In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('../Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-19,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-19,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-19,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-19,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-19,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [6]:
# Transformed several columns to numerical values
df_encoded = pd.get_dummies(df, columns=["home_ownership", "issue_d", "verification_status", "pymnt_plan", "initial_list_status", "application_type", "next_pymnt_d", "hardship_flag", "debt_settlement_flag"])
df_encoded.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,next_pymnt_d_Apr-19,next_pymnt_d_May-19,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,0,1,0,1,1,0,0,1,1,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,1,0,1,1,0,0,1,1,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,1,0,1,1,0,0,1,1,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,1,0,1,1,0,0,1,1,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,0,1,0,1,1,0,0,1,1,1

# Split the Data into Training and Testing

In [7]:
# Create our features
X = df_encoded.drop(columns="loan_status")

# Create our target
y = df_encoded["loan_status"]

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,next_pymnt_d_Apr-19,next_pymnt_d_May-19,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.148001,1.0,0.123879,0.876121,0.860340,0.139660,0.383161,0.616839,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.355104,0.0,0.329446,0.329446,0.346637,0.346637,0.486161,0.486161,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [9]:
# Check the balance of our target values
df['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [10]:
# Split the X and y into X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({'low_risk': 51366, 'high_risk': 246})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [43]:
# Resample the training data with the RandomOversampler
# YOUR CODE HERE
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [44]:
Counter(y_resampled)

Counter({'low_risk': 51366, 'high_risk': 51366})

In [45]:
# Create a random forest classifier. Random state = 1.
rf_model = RandomForestClassifier(n_estimators=128, random_state=1)

In [46]:
# Fitting the model
rf_model = rf_model.fit(X_resampled, y_resampled)

In [47]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_resampled)

In [48]:
predictions

array(['low_risk', 'low_risk', 'low_risk', ..., 'high_risk', 'high_risk',
       'high_risk'], dtype=object)

In [49]:
## Generate a confusion matrix with the results

y_pred = rf_model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   31,    70],
       [    7, 17097]], dtype=int64)

In [50]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.653260716038863

In [51]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.82      0.31      1.00      0.45      0.55      0.29       101
   low_risk       1.00      1.00      0.31      1.00      0.55      0.33     17104

avg / total       0.99      1.00      0.31      0.99      0.55      0.33     17205

In [52]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([1.19012555e-02, 2.89158866e-02, 2.15154802e-02, 1.38244610e-02,
       1.64474039e-02, 2.28237311e-03, 3.57523294e-03, 6.51368397e-03,
       1.39590980e-03, 1.35329691e-02, 8.11206696e-03, 1.85451227e-02,
       1.87875844e-02, 6.18416361e-02, 5.81005187e-02, 9.09118339e-02,
       6.42240975e-02, 1.01332105e-02, 0.00000000e+00, 0.00000000e+00,
       6.77207059e-02, 3.43756178e-04, 0.00000000e+00, 0.00000000e+00,
       3.44095160e-03, 1.27935025e-02, 4.63449212e-03, 5.70818897e-03,
       3.37988614e-03, 6.33591818e-03, 1.18621176e-02, 1.14220998e-02,
       9.96057027e-03, 3.52938063e-03, 4.83505880e-03, 1.31991552e-02,
       1.03528320e-02, 9.62908887e-03, 6.68144592e-03, 5.72041371e-03,
       6.94270961e-03, 7.38301101e-03, 1.47026166e-02, 1.24530206e-02,
       1.19292848e-02, 4.24767949e-05, 1.11439241e-06, 1.22548804e-02,
       1.36213696e-02, 8.48073334e-03, 6.10370293e-03, 4.60069613e-03,
       1.09281915e-02, 1.56804002e-02, 2.20874068e-03, 5.00904558e-03,
       5.97278251e-03, 4.80538789e-03, 7.61472808e-03, 7.93206654e-03,
       6.95093976e-03, 7.92462878e-03, 6.02980543e-03, 7.24544286e-03,
       0.00000000e+00, 0.00000000e+00, 4.52856643e-04, 5.48455688e-03,
       8.61030307e-03, 6.25727720e-03, 1.09909045e-03, 0.00000000e+00,
       1.25331774e-02, 1.25559626e-02, 1.37624382e-02, 9.87886309e-03,
       1.13795940e-04, 1.60519123e-03, 1.24707345e-03, 1.59691204e-03,
       1.00198223e-02, 3.00624432e-02, 2.86629608e-02, 1.40278246e-03,
       1.30736927e-03, 1.19991082e-03, 0.00000000e+00, 1.03840841e-03,
       1.25571592e-03, 1.31561572e-03, 1.29711192e-03, 9.86213776e-03,
       8.45015605e-03, 0.00000000e+00, 0.00000000e+00])

In [53]:
# Sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.09091183388621257, 'total_rec_prncp'),
 (0.06772070586529556, 'last_pymnt_amnt'),
 (0.06422409749892535, 'total_rec_int'),
 (0.06184163608402334, 'total_pymnt'),
 (0.05810051865504274, 'total_pymnt_inv'),
 (0.030062443232260167, 'issue_d_Jan-19'),
 (0.028915886583561267, 'int_rate'),
 (0.028662960795354003, 'issue_d_Mar-19'),
 (0.021515480163573932, 'installment'),
 (0.01878758443646364, 'out_prncp_inv'),
 (0.01854512270531555, 'out_prncp'),
 (0.016447403931104856, 'dti'),
 (0.015680400183127625, 'mths_since_recent_inq'),
 (0.014702616620733707, 'avg_cur_bal'),
 (0.013824460952011626, 'annual_inc'),
 (0.013762438177977754, 'total_bc_limit'),
 (0.013621369601028289, 'mo_sin_old_rev_tl_op'),
 (0.013532969130693786, 'revol_bal'),
 (0.013199155184754629, 'max_bal_bc'),
 (0.012793502456266094, 'tot_cur_bal'),
 (0.012555962613122217, 'total_bal_ex_mort'),
 (0.012533177440323066, 'tot_hi_cred_lim'),
 (0.012453020555841026, 'bc_open_to_buy'),
 (0.01225488036943016, 'mo_sin_old_il_acct'),
 (0.011929284846822942, 'bc_util'),
 (0.011901255500309717, 'loan_amnt'),
 (0.011862117594818807, 'mths_since_rcnt_il'),
 (0.011422099751672393, 'total_bal_il'),
 (0.010928191546490008, 'mths_since_recent_bc'),
 (0.010352832040233262, 'all_util'),
 (0.010133210474844685, 'total_rec_late_fee'),
 (0.010019822312839056, 'issue_d_Feb-19'),
 (0.009960570270491648, 'il_util'),
 (0.009878863089355384, 'total_il_high_credit_limit'),
 (0.009862137762176752, 'next_pymnt_d_Apr-19'),
 (0.009629088873352992, 'total_rev_hi_lim'),
 (0.008610303067101912, 'pct_tl_nvr_dlq'),
 (0.008480733336543828, 'mo_sin_rcnt_rev_tl_op'),
 (0.008450156045931195, 'next_pymnt_d_May-19'),
 (0.008112066962238738, 'total_acc'),
 (0.007932066538209579, 'num_il_tl'),
 (0.007924628783059664, 'num_rev_accts'),
 (0.0076147280793108195, 'num_bc_tl'),
 (0.007383011013523586, 'acc_open_past_24mths'),
 (0.007245442860562043, 'num_sats'),
 (0.0069509397622932465, 'num_op_rev_tl'),
 (0.0069427096067680265, 'inq_last_12m'),
 (0.006681445922987035, 'inq_fi'),
 (0.006513683969695747, 'open_acc'),
 (0.006335918178328572, 'open_il_24m'),
 (0.006257277197987043, 'percent_bc_gt_75'),
 (0.006103702932516271, 'mo_sin_rcnt_tl'),
 (0.006029805434143855, 'num_rev_tl_bal_gt_0'),
 (0.005972782513044126, 'num_actv_rev_tl'),
 (0.0057204137060257705, 'total_cu_tl'),
 (0.005708188968491213, 'open_act_il'),
 (0.005484556883654537, 'num_tl_op_past_12m'),
 (0.005009045577755728, 'num_actv_bc_tl'),
 (0.004835058802889594, 'open_rv_24m'),
 (0.004805387893517364, 'num_bc_sats'),
 (0.004634492120440761, 'open_acc_6m'),
 (0.004600696126673962, 'mort_acc'),
 (0.003575232939400237, 'inq_last_6mths'),
 (0.003529380628305006, 'open_rv_12m'),
 (0.003440951597906914, 'tot_coll_amt'),
 (0.0033798861361953956, 'open_il_12m'),
 (0.002282373110444605, 'delinq_2yrs'),
 (0.0022087406844254606, 'num_accts_ever_120_pd'),
 (0.001605191229999864, 'home_ownership_MORTGAGE'),
 (0.0015969120390703943, 'home_ownership_RENT'),
 (0.0014027824642180982, 'verification_status_Not Verified'),
 (0.0013959097956437849, 'pub_rec'),
 (0.0013156157241640005, 'application_type_Individual'),
 (0.0013073692668440968, 'verification_status_Source Verified'),
 (0.001297111918654954, 'application_type_Joint App'),
 (0.0012557159167058784, 'initial_list_status_w'),
 (0.0012470734500814244, 'home_ownership_OWN'),
 (0.0011999108188535323, 'verification_status_Verified'),
 (0.0010990904535260549, 'pub_rec_bankruptcies'),
 (0.0010384084074958621, 'initial_list_status_f'),
 (0.00045285664319240327, 'num_tl_90g_dpd_24m'),
 (0.0003437561775595792, 'collections_12_mths_ex_med'),
 (0.00011379594049302458, 'home_ownership_ANY'),
 (4.247679486245499e-05, 'chargeoff_within_12_mths'),
 (1.1143924121555975e-06, 'delinq_amnt'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [54]:
# Train the Classifier

from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification

# Create adaboost classifier object
clf = AdaBoostClassifier(n_estimators=128, random_state=1)

#Train Adaboost Classifier
model2 = clf.fit(X_resampled, y_resampled)

y_pred2 = model2.predict(X_test)

In [55]:
# Calculated the balanced accuracy score

clf.score(X, y)

0.9810366624525917

In [56]:
# Display the confusion matrix

confusion_matrix(y_test, y_pred2)

array([[   80,    21],
       [  319, 16785]], dtype=int64)

In [57]:
# Print the imbalanced classification report

print(classification_report_imbalanced(y_test, y_pred2))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.20      0.79      0.98      0.32      0.88      0.76       101
   low_risk       1.00      0.98      0.79      0.99      0.88      0.79     17104

avg / total       0.99      0.98      0.79      0.99      0.88      0.79     17205